# Generated by Django 3.0.3 on 2020-03-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField()),
                ('EmpName', models.CharField(max_length=50)),
                ('EmpSal', models.IntegerField()),
                ('EmpLoc', models.CharField(max_length=50)),
            ],
        ),
    ]
